plugins:
  - jekyll-seo-tag

title: JTransit - Cebu Jeepney Navigation
description: Must have app for commuters in Cebu. JTransit provides one or more ways to navigate the city via public transportation. Suggests Jeepney routes and calculates fare.
url: https://jtransit.github.io/
author: Boscafsoftware